const GET_COIN_LIST_REQUEST = 'GET_COIN_LIST_REQUEST'
const GET_COIN_LIST_SUCCESS = 'GET_COIN_LIST_SUCCESS'
const GET_COIN_LIST_FAILURE = 'GET_COIN_LIST_FAILURE'

export const coinConstantsIndex = {
    GET_COIN_LIST_REQUEST,
    GET_COIN_LIST_SUCCESS,
    GET_COIN_LIST_FAILURE,
}

