const COIN_LIST_REQUEST = 'COIN_LIST_REQUEST'
const COIN_LIST_SUCCESS = 'COIN_LIST_SUCCESS'
const COIN_LIST_FAILURE = 'COIN_LIST_FAILURE'

export const coinConstantsIndex = {
    COIN_LIST_REQUEST,
    COIN_LIST_SUCCESS,
    COIN_LIST_FAILURE,
}