const GET_COIN_LOCAL_STORAGE_REQUEST = 'GET_COIN_LOCAL_STORAGE_REQUEST'
const GET_COIN_LOCAL_STORAGE_SUCCESS = 'GET_COIN_LOCAL_STORAGE_SUCCESS'
const GET_COIN_LOCAL_STORAGE_FAILURE = 'GET_COIN_LOCAL_STORAGE_FAILURE'

const SET_COIN_LOCAL_STORAGE_REQUEST = 'SET_COIN_LOCAL_STORAGE_REQUEST'
const SET_COIN_LOCAL_STORAGE_SUCCESS = 'SET_COIN_LOCAL_STORAGE_SUCCESS'
const SET_COIN_LOCAL_STORAGE_FAILURE = 'SET_COIN_LOCAL_STORAGE_FAILURE'

const DELETE_COIN_LOCAL_STORAGE_REQUEST = 'DELETE_COIN_LOCAL_STORAGE_REQUEST'
const DELETE_COIN_LOCAL_STORAGE_SUCCESS = 'DELETE_COIN_LOCAL_STORAGE_SUCCESS'
const DELETE_COIN_LOCAL_STORAGE_FAILURE = 'DELETE_COIN_LOCAL_STORAGE_FAILURE'

export const localStorageConstantsIndex = {
    GET_COIN_LOCAL_STORAGE_REQUEST,
    GET_COIN_LOCAL_STORAGE_SUCCESS,
    GET_COIN_LOCAL_STORAGE_FAILURE,
    SET_COIN_LOCAL_STORAGE_REQUEST,
    SET_COIN_LOCAL_STORAGE_SUCCESS,
    SET_COIN_LOCAL_STORAGE_FAILURE,
    DELETE_COIN_LOCAL_STORAGE_REQUEST,
    DELETE_COIN_LOCAL_STORAGE_SUCCESS,
    DELETE_COIN_LOCAL_STORAGE_FAILURE,
}